### ISSUE TITLE
Opt: use DataTypes.UUIDV1 to fill txid

### ISSUE THREAD

**Issue by eigmax** [ieigen/eigen_service#26]
@Weber-H2O2  Plz migrates all the multisig transactions to `database_multisig`, and replaces the code https://github.com/ieigen/eigen_service/blob/main/src/model/database_multisig.ts#L117 by `sequelize` built-in default initiator. 

https://sequelize.org/v6/variable/index.html#static-variable-DataTypes

**Comment by Weber-H2O2** [comment]
OK. I'll try it ASAP.

**Comment by Weber-H2O2** [comment]
Can be closed if #27 is merged.
